# Note: 192.168.123.xxx is an example network, you must update all these to match your own.

version: '2.1'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.5.1
    hostname: pihole
    domainname: home.indiegigs.com             # <-- Update
    cap_add:
      - NET_ADMIN
    networks:
      docker_network:
        ipv4_address: 192.168.1.3   # <-- Update
#        ipv6_address: 2a02:8010:6253:0:0:0:1:2
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 192.168.1.3         # <-- Update (match ipv4_address)
 #     ServerIPv6: 2a02:8010:6253:0:0:0:1:2
      VIRTUAL_HOST: pihole.home.indiegigs.com  # <-- Update (match hostname + domainname)
      WEBPASSWORD: ""                   # <-- Add password (if required)
    volumes:
      - ../pihole/resolv.conf:/etc/resolv.conf
      - ../pihole/data:/etc/pihole
    restart: unless-stopped
  unifi:
     container_name: unifi-controller
     image: jacobalberty/unifi:5.14.23
     hostname: unifi
     domainname: home.indiegigs.com             # <-- Update
     cap_add:
       - NET_ADMIN
     networks:
      docker_network:
        ipv4_address: 192.168.1.4   #M-BM- <-- Update
     dns:
      - 127.0.0.1
      - 8.8.8.8
     ports:
      - 443/tcp
      - 80/tcp
     volumes:
      - ./unifi:/unifi
  grafana:
    image: grafana/grafana:7.5.3
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./teslamate/grafana/dashboards:/teslamate
    environment:
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    restart: always
    links:
      - node-exporter
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=900d"
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./secrets/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
  node-exporter:
    privileged: true
    image: prom/node-exporter:v1.1.1
    container_name: node-exporter
    restart: always
    network_mode: host
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /volume1:/volume1:ro
    command:
      - "--log.level=debug"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1/@docker)($$|/)"
  zyxel:
    image: andrewjw/zyxelprometheus:0.5.2
    container_name: zyxel
    ports:
      - 9101:9100
    env_file:
      - ./secrets/zyxel
  glowprom:
    image: andrewjw/glowprom:0.2.5
    container_name: glowprom
    ports:
      - 9102:9100
    env_file:
      - ./secrets/glowprom
  mythtv:
     image: instantlinux/mythtv-backend:29.1-fixes.201909121531.4c432df
     hostname: mythtv
     container_name: mythtv
     restart: always
     volumes:
        - /volume1/mythtv:/mnt/nfs/mythtv2
        - ./secrets/mythtv-db-password:/run/secrets/mythtv-db-password:ro
     environment:
        - DBNAME=mythconverg
        - DBSERVER=mariadb
     depends_on:
        - mariadb
     ports:
        - 4001:80
        - 2022:2022
        - 6543:6543
        - 6544:6544
        - 6549:6549
        - 6554:6554
        - 6760:6760
  mariadb:
    image: mariadb:10.5.6-focal
    container_name: mariadb
    restart: always
    volumes:
       - ./mariadb:/var/lib/mysql
    env_file:
       - ./secrets/mariadb
    ports:
       - 3306:3306
  teslamate:
    image: teslamate/teslamate:1.21.3
    container_name: teslamate
    restart: always
    environment:
      - DATABASE_HOST=database
      - MQTT_HOST=mqtt
      - DISABLE_MQTT=true
    env_file:
      - ./secrets/teslamate
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
    ports:
      - 4000:4000
    depends_on:
      - database
  database:
    image: postgres:12
    container_name: postgres
    restart: always
    env_file:
      - ./secrets/postgres
    volumes:
      - ./teslamate-db:/var/lib/postgresql/data
    ports:
      - 5433:5432
  code:
    image: theiaide-custom:latest
    container_name: code
    restart: always
    volumes:
      - /var/services/homes/andrew/programming:/home/project
      - ./secrets/code-ssh:/home/theia/.ssh
    ports:
      - 9000:3000
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: jekyll
    restart: always
    command: jekyll serve --drafts --future --trace
    volumes:
      - /var/services/homes/andrew/programming/site:/srv/jekyll
    ports:
      - 9001:4000
    environment:
      - MAKEFLAGS=-j4
  buildbot:
    image: buildbot/buildbot-master:master
    container_name: buildbot
    env_file:
      - ./secrets/buildbot
    environment:
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://192.168.1.207:8010/
      - BUILDBOT_WEB_PORT=tcp:port=8010
    ports:
      - "8010:8010"
    volumes:
      - ./buildbot.cfg:/var/lib/buildbot/master.cfg
      - ./buildbot-db:/var/lib/buildbot/db
      - ./secrets/buildbot:/secrets
    logging:
      options:
        max-size: "10m"
        max-files: "3"
  worker:
    image: "worker"
    container_name: worker
    environment:
      BUILDMASTER: buildbot
      BUILDMASTER_PORT: 9989
      WORKERNAME: buildbot-docker
      WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    env_file:
       - ./secrets/worker
    volumes:
      - ./secrets/worker-ssh:/home/buildbot/.ssh
networks:
  docker_network:
    enable_ipv6: false
    driver: macvlan
    driver_opts:
      parent: eth1
    ipam:
      config:
        - subnet: 192.168.1.0/24            # <-- Update
          gateway: 192.168.1.1              # <-- Update
          ip_range: 192.168.1.3/28        # <-- Update
       # - subnet: 2a02:8010:6253:0:0:0:1:1/48
